# Generated by Django 2.2.28 on 2023-08-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='btc_balance',
            field=models.FloatField(default=8.527280427674821),
        ),
    ]
