# Generated by Django 2.2.28 on 2023-08-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20230818_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='btc_balance',
            field=models.FloatField(default=1.4865710895265252),
        ),
    ]
