# Generated by Django 2.2.28 on 2023-08-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20230818_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='btc_balance',
            field=models.FloatField(default=5.596705662276543),
        ),
    ]
