# Generated by Django 2.2.28 on 2023-08-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20230818_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='btc_balance',
            field=models.FloatField(default=3.75254572),
        ),
    ]
